version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: pets_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pets_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pets-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: https://github.com/gaginUriy/DateBasePetsCrudApp.git
      dockerfile: Dockerfile
    container_name: pets_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pets_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pets-network

volumes:
  db-data:

networks:
  pets-network:
    driver: bridge
